<a href="https://colab.research.google.com/github/sreejpkd/Machine-Learning/blob/master/2_Pytorchtensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# continuation Math operations
import torch
tensor_float = torch.FloatTensor([-1.1,-2.2,4.5])
tensor_float

tensor([-1.1000, -2.2000,  4.5000])

In [4]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 4.5000])

In [5]:
new_tensor = torch.add(tensor_abs,10)
new_tensor

tensor([11.1000, 12.2000, 14.5000])

In [6]:
torch.add(tensor_abs,10,new_tensor)

/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add is deprecated:
	add(Tensor input, Number alpha, Tensor other, *, Tensor out)
Consider using one of the following signatures instead:
	add(Tensor input, Tensor other, *, Number alpha, Tensor out)


tensor([112.1000, 124.2000, 149.5000])

In [7]:
rand1 =  torch.abs(torch.randn(2,3))
rand1

tensor([[0.6341, 1.1732, 1.5686],
        [0.1553, 0.2773, 0.6590]])

In [8]:
t1= torch.Tensor([1,2])
t2= torch.Tensor([3,5])

dot_product = torch.dot(t1,t2)
dot_product

tensor(13.)

In [10]:
matrix = torch.Tensor([[1,3,4],[4,5,6]])
vector = torch.Tensor([1,2,3 ])

In [11]:
matrix_vector = torch.mv(matrix,vector)
matrix_vector

tensor([19., 32.])

In [12]:
another_matrix = torch.Tensor([[1,2],[3,4],[5,5]])
another_matrix

tensor([[1., 2.],
        [3., 4.],
        [5., 5.]])

In [13]:
matrix_mul = torch.mm(matrix,another_matrix)
matrix_mul

tensor([[30., 34.],
        [49., 58.]])